### ISSUE TITLE
FR: resolve `~` in the file paths

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#1]
Most apps automatically resolve the `~` to the home folder. This is particularly useful when you work on different devices, since the file path still works even if the username is different.

```
# this works
/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Dotfolder/Configs/pandoc/main-bibliography.bib

# this does not work, but would be useful if it did
~/Library/Mobile Documents/com~apple~CloudDocs/Dotfolder/Configs/pandoc/main-bibliography.bib
```

**Comment by mgmeyers** [comment]
I'll see if this is doable. There are a lot of quirks to executing shell commands from Electron.
