### ISSUE TITLE
the reference will display twice

### ISSUE THREAD

**Issue by EroyalBoy** [mgmeyers/obsidian-pandoc-reference-list#11]
i utilize the chinese csl ,gb7714-2015-numeric, but emerging this issues
![CleanShot 2022-05-01 at 11 37 41@2x png](https://user-images.githubusercontent.com/36374478/166131242-eb986b70-08fc-4c0d-930a-e0eaf3358193.png)

**Comment by mgmeyers** [comment]
Hmm 🤔 I'm not sure if there's much I can do about this @EroyalBoy, I use the output that pandoc produces to create the sidebar. Does this CSL work for you when you run pandoc from the command line?

**Comment by EroyalBoy** [comment]
> Hmm 🤔 I'm not sure if there's much I can do about this @EroyalBoy, I use the output that pandoc produces to create the sidebar. Does this CSL work for you when you run pandoc from the command line?

yes, when i used this CSL, it don't happen any issues

**Comment by mgmeyers** [comment]
@EroyalBoy What pandoc command do you run in the commandline when using your CSL file?

**Comment by wenbopeng** [comment]
> i utilize the chinese csl ,gb7714-2015-numeric, but emerging this issues ![CleanShot 2022-05-01 at 11 37 41@2x png](https://user-images.githubusercontent.com/36374478/166131242-eb986b70-08fc-4c0d-930a-e0eaf3358193.png)

Showing it twice is a problem with this csl and pandoc. Don't use third-party made bilingual csl for zotero. You will find that the results generated by pandoc are duplicate references if you run the shell command.

**Comment by mgmeyers** [comment]
This should be fixed in the latest version of the plugins. Feel free to open another issue if you still have problems with this.
