### ISSUE TITLE
Bigger fonts

### ISSUE THREAD

**Issue by jsmm** [mgmeyers/obsidian-pandoc-reference-list#12]
Would it be possible to increase the font size?
Other than the tiny font, this is a great plugin to have. Thanks for sharing it.

**Comment by mgmeyers** [comment]
Thanks @jsmm I have plans to add style settings support, which should allow adjusting the font size. Closing this issue in favor of #21

**Comment by mgmeyers** [comment]
@jsmm You can now control the font size using the styles setting plugin!
