### ISSUE TITLE
Bug: citekey tooltips do not work when citation has page number

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#13]
this does not work: 
```md
[@RammertEtAl2016, p. 12]
```

this does work: 
```md
[@RammertEtAl2016]
```

**Comment by chrisgrieser** [comment]
actually, this issue has not been resolved me :(

**Comment by mgmeyers** [comment]
Hmm, strange. Does the cite include the comma when you inspect it?

<img width="830" alt="Screen Shot 2022-05-02 at 11 38 51 AM" src="https://user-images.githubusercontent.com/2694747/166305609-b66365ff-6b89-4b01-bd4d-0b08b26e23a9.png">

**Comment by chrisgrieser** [comment]
nope, it does not. the citekey is indeed correct.
<img width="513" alt="Pasted image  2022-05-03 00 10 51" src="https://user-images.githubusercontent.com/73286100/166335483-ad5d5dc4-5118-48d2-820e-8fd3f6f0327a.png">
<img width="512" alt="Pasted image  2022-05-03 00 11 27" src="https://user-images.githubusercontent.com/73286100/166335513-00ecc5b9-0b8c-429b-afc7-06ff8bf9f180.png">

**Comment by mgmeyers** [comment]
Oh, hmm... Does the citation show for @Luhmann1998 in the sidebar?

**Comment by chrisgrieser** [comment]
yes, all items show correctly in the sidebar. only the hover tooltip isn't working for those that have page numbers (or any other text) following the citekey.
