### ISSUE TITLE
BUG: cssclass for pandoc citaitons gets applied at the wrong places

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#14]
- since it adds an extra element inside `.cm-hmd-bare-link`, the snippet for highlighting of pandoc citation breaks for people
- the class also gets applied to footnotes (`[^1]`), which results in wrong assigning of the pandoc-extras class to normal test. (in the following screenshot, `.cm-pandoc-citation-extra` has been highlighted yellow via css)

![Pasted image  2022-05-02 01 38 39](https://user-images.githubusercontent.com/73286100/166169232-cd370b91-41d2-44a5-a699-0e6ae20e7e0c.png)

**Comment by mgmeyers** [comment]
@chrisgrieser Would you mind sending me this paragraph? I can't seem to repro

**Comment by chrisgrieser** [comment]
no need – it seems fixing #16 may have fixed this as well.
