### ISSUE TITLE
Bug: Tooltips sometimes get cut off

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#15]
depending on the location of the pandoc citation, tooltips sometimes get cut off: 
![Pasted image  2022-05-02 01 42 43](https://user-images.githubusercontent.com/73286100/166169406-f689e4c0-955a-416f-8666-7416c66cb408.png)

**Comment by Phurga** [comment]
I still have this issue but it happens when the CSL style contains the URL properties, and only in cases where there is a long URL and no "-" allowing to break lines but keep the URL in one piece.

![Image](https://github.com/user-attachments/assets/262a23fa-3f1e-412d-9a13-3089ad74a565)
