### ISSUE TITLE
Bug: In Reading Mode, Plugin duplicates content and does weird content changes

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#16]
Compare the Source Mode and the Reading mode of the very same paragraph. (all your pandoc css classes are marked yellow here.)

some parts now appears three times, the assigning of the css class is off, and for whatever reason some words get randomly cut off.

https://user-images.githubusercontent.com/73286100/166169975-c5f985d2-14ce-485d-b294-f3773295cb04.mov

**Comment by mgmeyers** [comment]
Waaah. Would you mind pasting that paragraph here @chrisgrieser?

**Comment by mgmeyers** [comment]
NVM, found a repro

**Comment by mgmeyers** [comment]
Think I fixed it. Let me know if you run into any more weirdness here
