### ISSUE TITLE
Copy entry and list doesn't work

### ISSUE THREAD

**Issue by tim-hilde** [mgmeyers/obsidian-pandoc-reference-list#17]
As the title says, copying an entry and the whole list doesn't work on my MacBook M1. Neither Alfred's clipboard manager saves it nor can I paste it.

**Comment by tim-hilde** [comment]
Actually, it still doesn't work correctly. If I copy an entry a) Alfred's clipboard manager doesn't get it and b) I cannot paste it into Obsidian.  Some other apps do work, e.g. Pages. On the other hand, this textbox doesn't allow it either.

**Comment by mgmeyers** [comment]
Hmm, yeah, you're right. Something weird is going on here. It seems to work sometimes but then will stop for some reason.

**Comment by mgmeyers** [comment]
Ok, I figured out what was going on here. There was a clash with one of obsidian's settings. I'm unfamiliar with how Alfred's clipboard manager works, so I'm not sure what can be done about that, but it should copy to your clipboard now.
