### ISSUE TITLE
FR: `pwc-tooltips` should appear earlier

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#18]
so on my machine (which is a fairly recent M1 mac), it still takes about a second of hovering before the tooltip appears. I assume this is due to the plugin running pandoc in the background? 

Anyway, I'd suggest that the tooltip box appears with a "loading" text as soon as hovered, and after finishing to load, insert the text into the tooltip. 

This may be a minor change, but I think it would be valuable, since right now, I have to hover the pandoc citation, wait a second, no pandoc citation appears, and then realize that my mouse wasn't close enough, reposition the mouse, etc.

**Comment by mgmeyers** [comment]
@chrisgrieser This is actually intentional. I set it to wait 1 second before opening tooltips. I'll add a setting to control this.
