### ISSUE TITLE
FR: Indicate invalid/non-existing citekeys

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#19]
in the sidebar as well as the tooltip (and maybe a css class for styling?), the plugin should indicate when a citekey cannot be found in the linked library.

this would help early on finding invalid citekeys (through typos, or deleting them from the library, etc.)

maybe as an optional toggle (since some people might simply use multiple bibtex libraries, and then this feature wouldn't be useful to them)

**Comment by mgmeyers** [comment]
Turns out this is pretty hard to do. I think it's doable, but it'll take some time to figure out the best way.

**Comment by chrisgrieser** [comment]
Mind elaborating why? I'd have assumed that this is pretty straightforward, since a citekey not found should be something you already detect? 🤔

**Comment by mgmeyers** [comment]
Yeah, basically I detect citekeys in editor/reading modes with a regular expression and don't look up anything about the citekey until it's time to display a tooltip. Then, to populate the tooltip, I pull the HTML out of the reference list in the sidebar. The main difficulty here is that the regular expression generally runs before we receive data from pandoc, so we have no reliable way to check that a citation for a citekey was returned. There are ways around this, but it requires updating reading/editing modes after they have already rendered.

**Comment by mgmeyers** [comment]
Ok, figured it out!

<img width="537" alt="Screen Shot 2022-05-04 at 3 03 14 PM" src="https://user-images.githubusercontent.com/2694747/166833061-fae804e4-9627-4ed8-a5a7-142695cc435f.png">
