### ISSUE TITLE
If all references are in Chinese, it will not be displayed. If Bibkey of one or more English references is used, it will be displayed normally.

### ISSUE THREAD

**Issue by wenbopeng** [mgmeyers/obsidian-pandoc-reference-list#2]
Thanks for the plugin, it's great!

A small issue. If all references are in Chinese, it will not be displayed(fig1). If Bibkey of one or more English references is used, it will be displayed normally(fig2).

fig1：
![fig1](https://s2.loli.net/2022/04/29/LtjSPCVgsdavD9I.jpg)

fig2:
![fig2](https://s2.loli.net/2022/04/29/qa65slbHjh87GrP.jpg)

**Comment by mgmeyers** [comment]
Thanks @wenbopeng, this should be fixed now. Let me know if you run into any issues
