### ISSUE TITLE
Add style settings to control all the things

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-pandoc-reference-list#21]
- Sidebar font / font-size
- Tooltip font / font-size
- Formatting / citekey / extra colors?
- Other stuff?

**Comment by mgmeyers** [comment]
@chrisgrieser Would you have any interest in setting this up? No worries if not, just though I'd throw it out there since you're familiar with style settings.

**Comment by chrisgrieser** [comment]
all the cool stuff I did like hiding URLs has already been done by you though :P So I wouldn't really know what do to here

but feel free to steal 🏴‍☠️ anything from me, its line 12832pp.
