### ISSUE TITLE
Bug: URLs in tooltips are weirdly cut off

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#23]
In general, the "hide links" setting should probably also affect URLs in tooltips anyway?

<img width="493" alt="Pasted image  2022-05-03 18 11 08" src="https://user-images.githubusercontent.com/73286100/166492572-41833d10-b64d-4672-a763-9aa23bfb9182.png">

**Comment by mgmeyers** [comment]
Ok, fixed the wrapping and also made the "hide links" setting apply to tooltips
