### ISSUE TITLE
Bug: BRAT stopped working

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#24]
<img width="469" alt="Pasted image  2022-05-03 22 19 03" src="https://user-images.githubusercontent.com/73286100/166559208-c7bf7612-7c8e-4201-ba1e-04ce497c5da8.png">

**Comment by Liong1976** [comment]
The same here

**Comment by mgmeyers** [comment]
Hmm, seems the release didn't go through. Should be fixed
