### ISSUE TITLE
Bug: `.pandoc-citation` also applied to text outside of `[]`

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#27]
<img width="413" alt="Pasted image  2022-05-05 18 46 27" src="https://user-images.githubusercontent.com/73286100/166972491-53a68ff2-daa7-4637-b86c-62b8de39a270.png">

I think in code blocks, and outside of square brackets, pandoc citation styling shouldn't apply. To my knowledge, Pandoc does not consider those valid, and this is a pandoc reference list plugin, after all.

I think a check whether a (potential) citekey occurs inside `.cm-hmd-barelink` would be one way for you to avoid checking for code blocks, inline code, yaml frontmatter, etc?

**Comment by mgmeyers** [comment]
So, citations outside of brackets are indeed valid. Eg:

<img width="319" alt="Screen Shot 2022-05-05 at 10 12 02 AM" src="https://user-images.githubusercontent.com/2694747/166976742-547b546b-1e56-422d-ad69-1b632b6b5814.png">

Converts to:

<img width="391" alt="Screen Shot 2022-05-05 at 10 13 02 AM" src="https://user-images.githubusercontent.com/2694747/166976893-99ac7e3b-743c-4774-ac10-82a7cfbe2b4c.png">

Turning off processing in code blocks makes sense. I wonder about yaml, though 🤔.

With pandoc you can add this to your yaml to add references without citing them in text:

```
---
nocite: @one, @two
---
```

I wonder if it would be valuable to check that these exist?

**Comment by chrisgrieser** [comment]
> So, citations outside of brackets are indeed valid.

huh, I didn't know that, actually. 

> I wonder if it would be valuable to check that these exist?Well, I don't have a use case for that (yet), but it probably wouldn't hurt? 🤔

**Comment by chrisgrieser** [comment]
(sorry, re-opening it since disabling in code blocks is still open)

**Comment by mgmeyers** [comment]
Disabled processing cite keys in codeblocks
