### ISSUE TITLE
FR: The tooltip information is footnote citation instead of bibliography

### ISSUE THREAD

**Issue by Liong1976** [mgmeyers/obsidian-pandoc-reference-list#29]
First of all, I would like to thank you for making this fantastic plugin.

I want to request to make the tooltip information as the footnote citation based on the citation style instead of the bibliography. For example, in the Chicago style citation, the information in the tooltip is Jack Kerouac, _The Dharma Bums_ (New York: Viking Press, 1958), 128. instead of Kerouac, Jack. _The Dharma Bums_. New York: Viking Press, 1958. While in the sidebar, it seems that it would be great if the reference is a bibliography.

**Comment by mgmeyers** [comment]
This should be fixed in the latest version of the plugin. Let me know if you run into any issues

**Comment by Liong1976** [comment]
Thank you, @mgmeyers! It looks great to me!
