### ISSUE TITLE
FR/Bug: Text in the side bar is not selectable

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#3]
While links in the sidebar can indeed be clicked, the text there cannot be selected, which would be useful for sharing bibliographies or something. 🙏

**Comment by mgmeyers** [comment]
So, it seem this is an obsidian thing that would take a lot of work to override. I may add a "copy" button instead, if that works for you @chrisgrieser

**Comment by chrisgrieser** [comment]
Too bad. But yeah, a copy button would be good then

**Comment by chrisgrieser** [comment]
Or rather, I think a command might be more useful. Allows hotkeys, and also saves space in the sidebar
