### ISSUE TITLE
Bug: when loading note/citation, the `.is-missing` gets applied

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#30]
When opening a note, or entering a new citation, it first gets rendered with `.is-missing`, then the citekey is apparently found and `.is-missing` is removed. This behavior results in very glitchy looks, since I styled my `.is-missing` with stark red.

The better solution would be to have citekeys that are still loading not have the `.is-missing` class, and apply that class only *after* the search for a citekey wasn't successful (as opposed to right now, where `.is-missing` is applied *as long as* the search isn't successful)

**Comment by mgmeyers** [comment]
@chrisgrieser I've added another class that should help out there, and renamed `.is-missing` for consistency

- If a citekey hasn't been checked yet, it won't have a modifier class
- If a citekey has been confirmed to exist, `.is-resolved` will be added
- If a citekey has been confirmed to not exist, `.is-unresolved` will be added

Let me know if this works for you.

**Comment by chrisgrieser** [comment]
well, I had to redo a bunch off CSS because all the styling for unresolved links also applied, but this seems to work fine.

(And the is-unresolved classname is probable beneficial for most themes)
