### ISSUE TITLE
[BUG]: Invalid citekeys don't get any cssclass anymore

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#32]
![image](https://user-images.githubusercontent.com/73286100/168186398-eb7521b0-c269-4efa-99fb-84892eb5a3ef.png)

**Comment by mgmeyers** [comment]
Hmm 🤔. Any errors in the console? Classes are only added after the reference list in the sidebar has been generated. So if that failed for some reason, I don't think the classes would be added. But something else could be going on here, too

**Comment by chrisgrieser** [comment]
Yeah it seems it only happens when there is no other valid citekey present in the current note. See here:
https://user-images.githubusercontent.com/73286100/168262521-858469f9-bd29-4d1d-b700-37aea7268e72.mov
