### ISSUE TITLE
FR: Literature Note Integration

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#34]
given that many people have their literature notes in a dedicated folder and with the citekey as filename, wouldn't it make sense to somehow integrate literature notes as well? Typing `[@Kieser2006a] [[Kieser2006a]]` all the time is a bit tedious, and also somewhat redundant.

Some ideas:
- display whether a citation has a literature note, e.g. with an icon (or cssclass for us theme devs)
- link/method to directly open the literature note.
- all while *not* changing the text in the markdown – for pandoc export, there should still only ever be `[@Kieser2006a]`

**Comment by mgmeyers** [comment]
I've been thinking about this, too @chrisgrieser. Would we assume literature notes are only one of:

- @citekey.md
- citekey.md

I imagine a lot of folks use other names. I can see looking up literature notes by a `citekey` metadata field, but I don't think there's a performant way of retrieving a file by metadata field. Maybe the above is the best way to start.

**Comment by lguenth** [comment]
It looks terrible but typing links as `[[litnote|[@citekey]]]` does technically work.

**Comment by FeralFlora** [comment]
This has been implemented right? So I think both this issue and #54 can be closed, unless there is some intention to expand the file names supported and implement the indicator that @chrisgrieser mentioned (if that was meant to be shown at the citation). Well, the tooltip has the literature note link too, so?
