### ISSUE TITLE
Bug: extras in multi-citations are not recognized properly

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#36]
<img width="1042" alt="Pasted image 2022-05-31 13 39 05" src="https://user-images.githubusercontent.com/73286100/171164894-1ca1e34e-0535-479e-9955-66284673fee1.png">

**Comment by mgmeyers** [comment]
@chrisgrieser This should be fixed (in theory). Feel free to open another issue if you run into any wierdness around pre/postfixes
