### ISSUE TITLE
Multiple entries of the same author in the same year don't show author names

### ISSUE THREAD

**Issue by tim-hilde** [mgmeyers/obsidian-pandoc-reference-list#37]
I've just come across an issue when having multiple entries of the same author in the same year: 

![SCR-20220602-lex](https://user-images.githubusercontent.com/44113468/171640281-a7be7e7a-8d47-4669-b8a1-72c209d65dcf.png)

As you can see the lower entry doesnt show the author's name.

**Comment by mgmeyers** [comment]
What CSL style are you using @tim-hilde?

**Comment by mgmeyers** [comment]
This should be fixed in the latest version. Feel free to open another issue if you still encounter problems with this.
