### ISSUE TITLE
Bug: Multiple Entries in Reading mode getting wrong separator

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#40]
![image](https://user-images.githubusercontent.com/73286100/176967991-ebb4d9c9-67ce-40a0-93c0-0808d5d71477.png)

the same section in source mode:
![Pasted image 2022-07-01 23 07 13](https://user-images.githubusercontent.com/73286100/176968026-f0582b01-a15a-46a3-808a-ffc4203aa7bd.png)

**Comment by mgmeyers** [comment]
@chrisgrieser Not sure what's going on here. This plugin doesn't change brackets to parenthesis. Is this something your theme does?

**Comment by chrisgrieser** [comment]
ugh, you are totally right, it's my theme 🙈 🤦 Sorry!
