### ISSUE TITLE
Unable to copy reference list(ObsidianV0.15.6)

### ISSUE THREAD

**Issue by wenbopeng** [mgmeyers/obsidian-pandoc-reference-list#41]
`No citations found in the active document.`

After updating Obsidian to version (V0.15.6), the reference list cannot be copied

![image](https://user-images.githubusercontent.com/74350447/178788933-581fe376-688e-4c80-a597-ed8f75f91181.png)

**Comment by mgmeyers** [comment]
Thanks @wenbopeng this should be fixed now. Let me know if you have any more issues with it.
