### ISSUE TITLE
FR: Supply path to a bibliography file relative to vault root folder

### ISSUE THREAD

**Issue by quctex** [mgmeyers/obsidian-pandoc-reference-list#43]
Now user must provide the absolute path to a bibliography file in plugin settings. This hinders sync settings between computers, as any absolute path may be different on another computer. 

My Feature Request is add option to provide path to bibliography relative to the current vault root folder. In this case, bibliography file must stored in vault. I suppose, this is common way to store bibliography file used with the obsidian notes. With this option syncing settings would be easier.

The requested option already provided by Citations plugin and BibNotes Formatter plugins. I believe one of those plugins handy to use with Pandoc Reference List plugin, and it would be good, if all of them configured in the same way.

**Comment by joezhouchenye** [comment]
A quick solution. Just modify the plugin's javascript code.

Change the 'resolveHome' function:

```javascript
function resolveHome(filepath) {
  if (filepath[0] === "~" && process.env.HOME) {
    return import_path.default.join(process.env.HOME, filepath.slice(1));
  }
  if (filepath[0] === ":") {
    let basepath = app.vault.adapter.getBasePath();
    return basepath + "/" + filepath.substr(1);
  }
  return filepath;
}
```

After this modification, we can add a ':' symbol in the front to indicate that it is a relative path.

**Comment by mgmeyers** [comment]
The plugin will now check for bibliography files relative to your vault root. Let me know if you have any issues with this.
