### ISSUE TITLE
Plugin stops working

### ISSUE THREAD

**Issue by tim-hilde** [mgmeyers/obsidian-pandoc-reference-list#44]
I've recently had the bug, that the plugin suddenly stops working. After reenabling it, it works again but after a few scrolls, it stops again.

The console outputs the following error:
![image](https://user-images.githubusercontent.com/44113468/184361667-2e17ad31-a945-4fcc-8a53-3d3ee81cd5f8.png)

**Comment by mgmeyers** [comment]
Should be fixed now @tim-hilde. Let me know if you still have issues.
