### ISSUE TITLE
How to change the citation style?

### ISSUE THREAD

**Issue by astroyh** [mgmeyers/obsidian-pandoc-reference-list#45]
This plugin could add a reference list as expected, but seemingly could not change the citation style such as '[@citekey]'. What I want is the '[@citekey]' could also be rendered in Pandoc format, given that some citekeys are very long. It would be nice if it could automatically rendering the citation written in Pandoc format as (author, year) or author (year). Could it be implemented or is there any alternative?

**Comment by mgmeyers** [comment]
This has been implemented in the latest version of the plugin.
