### ISSUE TITLE
Select reference from list

### ISSUE THREAD

**Issue by amzon-ex** [mgmeyers/obsidian-pandoc-reference-list#46]
Hi, is it possible to insert a citekey from a list generated from the bibtex within Obsidian? Currently I open zotero, quickcopy the citekey and then insert it. 
(Please feel free to suggest me a better method if possible).

Generating a list of reference is all I'd wanted, and this plugin does that excellently so far. However, obtaining the citekeys seems tedious.

**Comment by agfaur** [comment]
If you use Zotero Integration (also from mgmeyers) you can turn on the option "Enable Cite Key Autocomplete". Then if you type '@' on any note while Zotero is running you should get a dropdown list with the metching cite keys as you start typing. Just be aware that it conflicts with the default for natural language dates plugin (in case you also use that).

**Comment by amzon-ex** [comment]
> If you use Zotero Integration (also from mgmeyers) you can turn on the option "Enable Cite Key Autocomplete". Then if you type '@' on any note while Zotero is running you should get a dropdown list with the metching cite keys as you start typing. Just be aware that it conflicts with the default for natural language dates plugin (in case you also use that).

Ahh I see, that works. Thank you.
Actually, I had considered using that plugin before, but it is all about features I don't use at all, so I had done away with it. In my case, it seems like an overkill.

**Comment by mgmeyers** [comment]
This plugin now has cite key autocompletion, which can be enabled through the plugin's settings
