### ISSUE TITLE
The reference order seems to be cached by the plugin.

### ISSUE THREAD

**Issue by joezhouchenye** [mgmeyers/obsidian-pandoc-reference-list#49]
Won't update the reference order if I change the file content order.

The references produced by the plugin:

![image](https://user-images.githubusercontent.com/59191277/207232489-5e8a5d13-a27d-4d72-8d23-d884a986898e.png)

And the references produced by converting to latex:

![image](https://user-images.githubusercontent.com/59191277/207232602-69372979-ec95-479f-a434-6a16d93396d9.png)

**Comment by mgmeyers** [comment]
This should be fixed in the latest version of the plugin
