### ISSUE TITLE
[FR]: Open linked citation file

### ISSUE THREAD

**Issue by DannyHatcher-Git** [mgmeyers/obsidian-pandoc-reference-list#54]
I use the Zotero integration plugin to bring my highlights into Obsidian.

Therefore, each citation in a file has a corresponding file in Obsidian.

Currently, the format is, [@cite] but this doesn't work with links.

By adding brackets like, [[@cite]] I can go to the file but then the pandoc export format is impacted.

Could we have a link in the side panel to navigate/find the corresponding file in Obsidian?

This could also then serve as a replacement for the backlinks/outgoing links panel specific to references.

**Comment by FeralFlora** [comment]
There is now a link to the literature note in the tooltip, and in the sidebar - given that you use the citekey as the filename.

**Comment by mgmeyers** [comment]
As @FeralFlora says, if a file exists with the same name as the cite key, there will be a link in the tooltip and the sidebar!

**Comment by CaoKang-David** [comment]
> As @FeralFlora says, if a file exists with the same name as the cite key, there will be a link in the tooltip and the sidebar!
Is it possible to modify the link to the format 'zotero://open-pdf/library/IWD2ZSC5?page=1'? This alteration would enable its opening through Zotero.

**Comment by dhbdev** [comment]
> > As @FeralFlora says, if a file exists with the same name as the cite key, there will be a link in the tooltip and the sidebar!
> > Is it possible to modify the link to the format 'zotero://open-pdf/library/IWD2ZSC5?page=1'? This alteration would enable its opening through Zotero.

Would be great if we have a option for that in the configuration form in Obsidian.
