### ISSUE TITLE
[SOLVED] Unable to open new note in Obsidian

### ISSUE THREAD

**Issue by diageo11** [mgmeyers/obsidian-pandoc-reference-list#55]
Whenever I create a new note while the Pandoc extension is enabled. I get this page which doesn't let me edit the file. It appears to have merged the "no file open" page with the new page at the bottom, which I can add text to, but does not show the page heading. Disabling the plugin allows me to open new notes again and shows these notes when I click on them. Apologies I am new to Obsidian so I don't know how to describe it better.

Running Obsidian v 1.1.9 and Pandoc v 1.2.10.
<img width="1251" alt="Screenshot 2023-01-09 at 13 42 48" src="https://user-images.githubusercontent.com/39025330/211331196-ee6ca212-2634-45a0-a091-17dff3847a4d.png">

**Comment by thesofakillers** [comment]
The same issue presents itself when trying to open notes in general. I get a popup saying 

"Cannot read properties of undefined (reading 'file')"

disabling the plugin fixes the issue. But basically this plugin is useless now.

Version 1.1.9 (Installer 0.14.15)

**Comment by thesofakillers** [comment]
@diageo11  try checking for updates to the plugin

settings > community plugins > check for updates
