### ISSUE TITLE
[BUG] Command failed with exit code 25

### ISSUE THREAD

**Issue by EhuddR** [mgmeyers/obsidian-pandoc-reference-list#58]
Hello!

I encountered this bug when validating the Pandoc configuration ![Screenshot_20230216_010124](https://user-images.githubusercontent.com/78237982/219281503-9404e59e-441e-409a-9ac6-a66b59a3afa1.png)

I have checked the .bib file at line 954, since that is the place where the plugin detects the error, however, I have not been able to solve the problem. Not only that, but I have tried deleting the entry that apparently has conflicts, but the error appears in the following entry.

I have used this tool: [Bibtex-tidy](https://github.com/FlamingTempura/bibtex-tidy) to try to fix the entries in the .bib file, but I did not get good results. Likewise, I would like to know why this error occurs and how to fix it.

Best regards.

**Comment by nndemeo** [comment]
Hi,

I was having the same issue. I resolved this by moving the .bib file to within my obsidian vault folder. I am not sure why or how this fixes it...

**Comment by EhuddR** [comment]
Hi! I resolved this using the latest pandoc V. 3.1 on Linux. This issue was listed on pandoc see [Issues 8604](https://github.com/jgm/pandoc/issues/8604) for more info.
