### ISSUE TITLE
[FR] Show a counter for the number of citations in the list

### ISSUE THREAD

**Issue by FeralFlora** [mgmeyers/obsidian-pandoc-reference-list#61]
It would be nice to quickly see how many citations I have added to a give document. Thus, a counter for this purpose would be great to have in the plugin.

**Comment by chrisgrieser** [comment]
the better word count plugin can be configured to show the number of citations in the current document: https://obsidian.md/plugins?id=better-word-count

**Comment by MSBack** [comment]
> the better word count plugin can be configured to show the number of citations in the current document: https://obsidian.md/plugins?id=better-word-count

Yeah, I know, but it misses a lot of citations: https://github.com/lukeleppan/better-word-count/issues/81

**Comment by FeralFlora** [comment]
I am closing this since the feature has been implemented.
