### ISSUE TITLE
No reaction since V2

### ISSUE THREAD

**Issue by ClusterWood** [mgmeyers/obsidian-pandoc-reference-list#64]
Since version 2 of "pandoc-reference-list," I only see the message "No citation found in the active document." Nothing else happens. The Pandoc validation is successful. It doesn't matter if and what I change in the options. When I switch back to version 1.2.11, the plugin works perfectly fine. 
What can I try to get to the root of the problem?

Windows 10
Obsidian 1.3.5
Pandoc Plugin 0.4.1
Pandoc 3.1.5
Zotero 6.0.26
BetterBibTex 6.7.93

**Comment by mgmeyers** [comment]
@ClusterWood Are there any errors in obsidian's developer console? You can open it with ctrl + shift + i / command + shift + i 

Also, check the plugin settings to make sure everything looks configured correctly. This was a major update, so some things may have changed there.

**Comment by ClusterWood** [comment]
No, nothing is displayed in the Developer Console regarding the plugin. Now I have just installed version 2.0.8. The message now shows the full citekey in the pop-up, but without @ But that's only since I access Zotero directly.

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/104789621/77bfa0b4-7f8d-4671-90b6-7a967a7f969e)

With 2.0.7:
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/104789621/5cb3b447-6357-46e7-b8a0-5b2d69c989f5)

And with 2.0.8:
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/104789621/a06515b1-1426-4fad-b769-2482c7ebaead)

**Comment by mgmeyers** [comment]
Hmm. So, you can try refreshing the bibliography:

<img width="259" alt="Screenshot 2023-07-15 at 10 19 31 AM" src="https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/2694747/fd1839ae-5b92-42e7-9cd5-f48533bfb05c">

If that doesn't help, would you be comfortable emailing me your bibliography file? hello@matthewmeye.rs You can also DM it to me if you're in the Obsidian discord server: https://discord.com/channels/686053708261228577/969644355042287717

**Comment by ClusterWood** [comment]
Yes, thanks, refreshing helps. Unfortunately, this process has to be repeated after every restart of Obsidian.

Many thanks

**Comment by mgmeyers** [comment]
@ClusterWood I think I figured out the issue. Try 2.0.9 and see if that works for you.

**Comment by ClusterWood** [comment]
Yes, now it works!
Thank you very much and have a nice Sunday

**Comment by maphouse** [comment]
Hi, I am having the same issues (though I just installed the plugin). 

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/4475249/61459dd8-f686-4c1b-bc3f-55379bdf5669)

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/4475249/c69180ef-9e92-48b3-9839-647c01d0caa0)


My pandoc is a portable latest version 3.1.8. It just doesn't seem to be reading my bibtex file based on the citekey links i'm entering.

**Comment by ShengliangD** [comment]
> Hi, I am having the same issues (though I just installed the plugin).
> 
> ![image](https://user-images.githubusercontent.com/4475249/273086855-61459dd8-f686-4c1b-bc3f-55379bdf5669.png)
> 
> ![image](https://user-images.githubusercontent.com/4475249/273086803-c69180ef-9e92-48b3-9839-647c01d0caa0.png)
> 
> My pandoc is a portable latest version 3.1.8. It just doesn't seem to be reading my bibtex file based on the citekey links i'm entering.

Seems to be related to the GFW:

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/19834894/3dff54a9-7f38-465e-9a80-eb8f43644c00)

Solution: Follow [this link](https://blog.csdn.net/qq_39367226/article/details/118703069) to update your hosts file. Then click the 'refresh bibliography' or relaunch obsidian.
