### ISSUE TITLE
Tooltips can't be interacted with

### ISSUE THREAD

**Issue by Bennibraun** [mgmeyers/obsidian-pandoc-reference-list#65]
It would be very handy to be able to interact with the text in tooltips i.e. to copy some of the citation or click a link.

**Comment by Bennibraun** [comment]
This could potentially be done by simply adding a check in showTooltip():
```typescript
showTooltip(el: HTMLSpanElement) {
  if (this.tooltip) {
    // Check if the pointer is still over the tooltip
    const tooltipRect = this.tooltip.getBoundingClientRect();
    const pointerX = event.clientX;
    const pointerY = event.clientY;
    if (
      pointerX >= tooltipRect.left &&
      pointerX <= tooltipRect.right &&
      pointerY >= tooltipRect.top &&
      pointerY <= tooltipRect.bottom
    ) {
      // Pointer is still over the tooltip, do not hide it
      return;
    }

    this.hideTooltip();
  }
  // etc.
```

And then the "pointerover" and "pointerout" listeners might need to be replaced with "mouseenter" and "mouseleave" so that they include descendants of the element:

```typescript
const over = (e: MouseEvent) => {
  // ...
  document.body.addEventListener('mouseenter', showTooltip);
};

const out = (e: MouseEvent) => {
  // ...
  document.body.addEventListener('mouseleave', hideTooltip);
};

document.body.addEventListener('mouseenter', '.pandoc-citation', over);
document.body.addEventListener('mouseleave', '.pandoc-citation', out);
```

But I haven't tested this so I might be way off. Would be cool if something like this could work though, I think it would make for an elegant interface.

**Comment by mgmeyers** [comment]
Thanks @Bennibraun I've adjusted the tooltips so they can be interacted with! Let me know if you run into any issues with this.

**Comment by Bennibraun** [comment]
Woah this works perfectly! Thanks so much, also that was apparently a lot more involved than I expected so kudos to you!
