### ISSUE TITLE
Using a custom csl file will invalidate this plugin

### ISSUE THREAD

**Issue by wenbopeng** [mgmeyers/obsidian-pandoc-reference-list#67]
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/74350447/82ca63ff-04f6-48a8-8ce0-cd1023b0d960)
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/74350447/26309660-bea5-42cc-bbd9-df833fd48569)
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/74350447/332384ed-c0a2-4a47-8800-43a9cde8762e)

Obsidian: 1.3.5
Obsidian Installer: 1.3.5
Zotero version: I use biblatex exported from Citavi, not Zotero
Pandoc version: 3.1.2
Pandoc Reference List version: 2.0.9

**Comment by YIRU69** [comment]
Same problem.

**Comment by mgmeyers** [comment]
Any errors in obsidian's developer console after selecting a custom citation style? You can open it with ctrl + shift + i / command + opt + i

**Comment by wenbopeng** [comment]
> Any errors in obsidian's developer console after selecting a custom citation style? You can open it with ctrl + shift + i / command + opt + i

I turned off all other plugins and only enabled this plugin. The issue still exists. 

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/74350447/51a087a5-743c-4945-8939-fb8539b44349)

**Comment by lisasuosuo** [comment]
same problem

**Comment by mgmeyers** [comment]
Hi all, could you share the CSL styles you're trying to use?

**Comment by lisasuosuo** [comment]
[000gb-t-7714-2015-numeric-bilingual.zip](https://github.com/mgmeyers/obsidian-pandoc-reference-list/files/12189226/000gb-t-7714-2015-numeric-bilingual.zip)
Thanks for reply

**Comment by wenbopeng** [comment]
[3csl.zip](https://github.com/mgmeyers/obsidian-pandoc-reference-list/files/12189244/csl.zip)

**Comment by mgmeyers** [comment]
Ok, I think I figured it out. Try updating to 2.0.15 and see if that fixes things for you.

**Comment by wenbopeng** [comment]
Perfect~! 2.0.15 solves this issue

**Comment by lisasuosuo** [comment]
Perfect！！It works

**Comment by khlee42** [comment]
It's still not working with 2.0.25. This is the csl file.

https://raw.githubusercontent.com/citation-style-language/styles/master/dependent/management-science.csl
