### ISSUE TITLE
Delay of the citekey prompt

### ISSUE THREAD

**Issue by xiaoqiangch** [mgmeyers/obsidian-pandoc-reference-list#69]
I have set the zotero library to be exported as .bib immediately after a document is added to library.
and I also turn on "Show Citeky Suggestions".
But in the obsidian, when I type "[@citekey]" ,the item just added won't show up. 
If I turn off and on again the "pandoc reference list" plugin in the setting, the just added item will show.
I believe there is something wrong with this.

**Comment by mgmeyers** [comment]
Hi @xiaoqiangch, bibliographies will not automatically be reloaded, but you can reload it manually using the status bar menu:

<img width="234" alt="Screenshot 2023-07-30 at 10 50 41 AM" src="https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/2694747/372600b2-776a-4e5f-bc29-886b3367a33c">

**Comment by xiaoqiangch** [comment]
You're right, I figured it out just now. Thanks anyway!
