### ISSUE TITLE
Handling when the same citekey is used more than once in an article

### ISSUE THREAD

**Issue by evolve2k** [mgmeyers/obsidian-pandoc-reference-list#7]
Super excited that you're building this plugin! 🤩

I noticed your test paragraph didnt include the common scenario where the same citekey may be used multiple times in a document.

I've had a quick look at the code and tests, but couldnt see a specific test for this scenario.

Desired feature is that a reference is generated once for each [unique] citekey on the page.

Keep up the good work!

**Comment by mgmeyers** [comment]
Hmm, @evolve2k does pandoc not take care of this automatically for you? Seems to on my end.

<img width="801" alt="Screen Shot 2022-04-29 at 4 51 15 PM" src="https://user-images.githubusercontent.com/2694747/166081568-b6da3cff-c61b-4881-89d1-6b6085d31ff5.png">

**Comment by evolve2k** [comment]
Ok great. Glad it does this already :)
Thanks, I'll close this issue.
