### ISSUE TITLE
Zotero integration not working

### ISSUE THREAD

**Issue by angelchimp** [mgmeyers/obsidian-pandoc-reference-list#73]
Hi, 

The plugin finds my Zotero library and attempts to import each of my folders, but has an error fetching their bibliographies. The error is: 
plugin:obsidian-pandoc-reference-list:79 Error fetching bibliography from Zotero Error: ENOENT: no such file or directory, open 'I:\OneDrive\Documents\Peatland Restoration Project\.pandoc\zotero-library-1.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at eval (plugin:obsidian-pand…erence-list:78:9024)
    at Generator.next (<anonymous>)
    at n (plugin:obsidian-pand…ference-list:6:1288)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I:\OneDrive\Documents\Peatland Restoration Project is the location of my vault, but not sure why it's trying to retrieve \.pandoc\zotero-library-1. I have pandoc installed but no extra arguments, and betterbibtex on zotero. What extra steps are needed here?

**Comment by angelchimp** [comment]
Thanks Matthew, it fixed itself after updating the plugin and restarting. Had to restart a few times but easily resolved.

I'm struggling more with exporting with pandoc into docx with bibliography/citations but I know this plugin doesn't explicitly handle that, so no worries.

Cheers!

**Comment by alexpghayes** [comment]
Had this issue but a few restarts also worked for me.
