### ISSUE TITLE
The pluge does not work

### ISSUE THREAD

**Issue by cyddgh** [mgmeyers/obsidian-pandoc-reference-list#76]
Hi, mgmeyers. Thank you for creating this plugin, but it does not run on my computer. I'm not sure if I'm doing something wrong or if there might be a bug in the plugin itself?

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/10444611/58eade84-9c91-4627-a7ea-e45d4a257810)

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/10444611/492cbbbc-d250-4250-99e1-1669bc32dae4)

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/10444611/5df74518-087c-4218-98f9-61b08113a3fd)

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/10444611/423effd6-0874-4144-a3d0-8e94e6bba9c0)

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/10444611/459e7604-83f6-4b28-9777-e622c8949fca)

![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/10444611/6390c539-83bc-4259-9f2c-9139827f94d7)

**Comment by ShengliangD** [comment]
Try this: #64

**Comment by ShengliangD** [comment]
Adding raw.githubusercontent.com items to hosts file worked for me, see #64 . The error in the debug console was different, not sure if it works for you.

**Comment by cyddgh** [comment]
Thanks. It is useful. 

I queried the real address of 'raw.githubusercontent.com' from 'https://sites.ipaddress.com/raw.githubusercontent.com/'. 
Then, I added these real addresses to the hosts file, which is located at 'C:\Windows\System32\drivers\etc'. 
After that, I ran 'ipconfig /flushdns' in the CMD to refresh DNS. 
Finally, I restarted Obsidian, and the plugins started working properly.

**Comment by cyddgh** [comment]
The issue has been resolved. it was due to a network problem.

**Comment by napseis** [comment]
I have the same problem but am not admin on my machine (and will never be), so the hostfile solution does not work for me...
I'm perfectly able to reach raw.githubusercontent.com from my web browser.
