### ISSUE TITLE
Feature request: Reference list automatically apends to bottom of the document when exporting

### ISSUE THREAD

**Issue by evolve2k** [mgmeyers/obsidian-pandoc-reference-list#8]
Automatic generation of a reference list/bibliography is a killer feature for any academics using Obsidian.

This plugin is clearly aimed at solving the automatic generation of a documents reference list from the cite keys which is Part 1.

Part 2 is being able to conveniently export the document **along with** the automatically generated reference list appended to the end of the document. 

At this stage I'd plan to use [obsidian-pandoc](https://github.com/OliverBalfour/obsidian-pandoc) plugin to export my document into word/pdf format to share with my supervisors/the broader academic community.

Please add functionality so that the reference list can be automatcially included as part of the document whenver the document is exported. 

Maybe we're talking a global setting in the plugin settings "Include references as part of the document when exporting", and a front matter that can be added to individiual documents to override this setting.  "auto-apend-reference-list-on-export"

**Comment by mgmeyers** [comment]
@evolve2k This is something pandoc can do for you. I don't use the obsidian pandoc plugin because it seems to be unmaintained. Instead I use the shell commands plugin to convert the active file in obsidian to docx. Here's the command I use, which automatically appends the reference list for me:

```
/usr/local/bin/pandoc {{folder_path:absolute}}/{{file_name}} -o {{folder_path:absolute}}/{{title}}.docx --citeproc --bibliography=/Users/matt/Documents/Pandoc/zotero.json --csl=/Users/matt/Documents/Pandoc/apa.csl --reference-doc=/Users/matt/Documents/Pandoc/essay-template.docx
```

**Comment by evolve2k** [comment]
The [Shell command plugin](https://publish.obsidian.md/shellcommands/Index) was the tip I needed. Thanks!
