### ISSUE TITLE
loading indefinitely with no error

### ISSUE THREAD

**Issue by eboswell** [mgmeyers/obsidian-pandoc-reference-list#90]
Hello,

thanks a lot for creating this useful plugin. I am unable to get my installation to work - the plugin loads indefinitely and never recognises any citations.
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/51829004/5e0ed072-0bd7-4a38-b151-06615643427a)
The reference name matches the name of the literature note file and also the citation key used in Zotero. 
The developer console shows no errors:
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/51829004/862a681a-ee00-420d-803b-2ba7a9640923)
This is my plugin configuration:
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/51829004/621cd052-bd7e-4f3a-a870-db04147b5405)
![image](https://github.com/mgmeyers/obsidian-pandoc-reference-list/assets/51829004/6bf87681-91fe-4abe-9b8e-640f341662af)

I am running this on Ubuntu 22.04.3, with Pandoc version 3.1.3 and Zotero version 6.0.30. I have the same setup on a different computer with Fedora 39 (same versions of Pandoc and Zotero), which works without issues.

How can I get this to work on my Ubuntu machine?

**Comment by wilenius** [comment]
Doesn't work for me either on Ubuntu 22.04, but I can't enable it either. Obsidian (v.1.5.8) hangs indefinitely, when I try to enable the plugin. Any ideas on how to debug this?

**Comment by eboswell** [comment]
it works for me now, probably due to some update.
