### ISSUE TITLE
After plugin update: inline citations but no references pane

### ISSUE THREAD

**Issue by vanhog** [mgmeyers/obsidian-pandoc-reference-list#96]
I'm using obsidian version 1.5.3 on Debian 12 (Bookworm). After updating the pandoc-reference-list plugin  to version 2.0.24 the citations/references pane of the right sidebar vanished, even though inline citations are properly resolved. Enabling/Disabling the plugin does not fix the problem. 

Rolling back to version 2.0.23 seems to be a workaround. 

Any ideas what went wrong?

**Comment by jteezy96** [comment]
same issue

**Comment by majdal** [comment]
There is a command to show the panel. Open the command pallet and search for "reference list" to show it. 

It's a recurring issue (https://github.com/mgmeyers/obsidian-pandoc-reference-list/issues/84). I hope @mgmeyers has the time to address it, or one of us steps up to help!

**Comment by vanhog** [comment]
Thank's a lot, @majdal. Trigger display of reference list via command pallet did the trick.
